import { Transfer, Team } from '@/types'

export const TEAMS: Team[] = [
  { id: 'alvark', name: 'アルバルク東京', short_name: 'A東京', division: 'B1', color: '#C8102E' },
  { id: 'utsunomiya', name: '宇都宮ブレックス', short_name: '宇都宮', division: 'B1', color: '#00529B' },
  { id: 'chiba', name: '千葉ジェッツ', short_name: '千葉J', division: 'B1', color: '#E4002B' },
  { id: 'kawasaki', name: '川崎ブレイブサンダース', short_name: '川崎', division: 'B1', color: '#003DA5' },
  { id: 'yokohama', name: '横浜DeNAビーコルズ', short_name: '横浜', division: 'B1', color: '#00A3E0' },
  { id: 'niigata', name: '新潟アルビレックスBB', short_name: '新潟', division: 'B1', color: '#F47920' },
  { id: 'toyama', name: '富山グラウジーズ', short_name: '富山', division: 'B1', color: '#002D62' },
  { id: 'mikawa', name: '三河シーホース', short_name: '三河', division: 'B1', color: '#003087' },
  { id: 'nagoya', name: '名古屋ダイヤモンドドルフィンズ', short_name: '名古屋D', division: 'B1', color: '#00843D' },
  { id: 'kyoto', name: '京都ハンナリーズ', short_name: '京都', division: 'B1', color: '#6F2C91' },
  { id: 'osaka', name: '大阪エヴェッサ', short_name: '大阪', division: 'B1', color: '#FF6900' },
  { id: 'shimane', name: '島根スサノオマジック', short_name: '島根', division: 'B1', color: '#C8102E' },
  { id: 'hiroshima', name: '広島ドラゴンフライズ', short_name: '広島', division: 'B1', color: '#C8102E' },
  { id: 'kumamoto', name: '熊本ヴォルターズ', short_name: '熊本', division: 'B1', color: '#002D62' },
  { id: 'ryukyu', name: '琉球ゴールデンキングス', short_name: '琉球', division: 'B1', color: '#003087' },
  { id: 'nagasaki', name: '長崎ヴェルカ', short_name: '長崎', division: 'B1', color: '#00529B' },
  { id: 'shiga', name: '滋賀レイクス', short_name: '滋賀', division: 'B1', color: '#002D62' },
  { id: 'saga', name: '佐賀バルーナーズ', short_name: '佐賀', division: 'B1', color: '#E4002B' },
]

export const MOCK_TRANSFERS: Transfer[] = [
  {
    id: '1',
    player_name: '田中 大貴',
    from_team: '千葉ジェッツ',
    to_team: 'アルバルク東京',
    status: 'transfer',
    announced_at: '2025-05-31',
    source_url: 'https://www.bleague.jp',
    source_name: 'Bリーグ公式',
    notes: null,
  },
  {
    id: '2',
    player_name: '比江島 慎',
    from_team: null,
    to_team: '宇都宮ブレックス',
    status: 'renewal',
    announced_at: '2025-05-30',
    source_url: null,
    source_name: '宇都宮ブレックス公式',
    notes: null,
  },
  {
    id: '3',
    player_name: '富樫 勇樹',
    from_team: null,
    to_team: '千葉ジェッツ',
    status: 'renewal',
    announced_at: '2025-05-29',
    source_url: null,
    source_name: '千葉ジェッツ公式',
    notes: null,
  },
  {
    id: '4',
    player_name: '谷口 大智',
    from_team: '琉球ゴールデンキングス',
    to_team: null,
    status: 'departure',
    announced_at: '2025-05-28',
    source_url: null,
    source_name: '琉球ゴールデンキングス公式',
    notes: null,
  },
  {
    id: '5',
    player_name: 'ジョシュ・スコット',
    from_team: null,
    to_team: '川崎ブレイブサンダース',
    status: 'new',
    announced_at: '2025-05-27',
    source_url: null,
    source_name: '川崎ブレイブサンダース公式',
    notes: 'NBA経験あり',
  },
  {
    id: '6',
    player_name: '安藤 誓哉',
    from_team: 'アルバルク東京',
    to_team: '島根スサノオマジック',
    status: 'transfer',
    announced_at: '2025-05-26',
    source_url: null,
    source_name: '島根スサノオマジック公式',
    notes: null,
  },
  {
    id: '7',
    player_name: '橋本 竜馬',
    from_team: null,
    to_team: '広島ドラゴンフライズ',
    status: 'renewal',
    announced_at: '2025-05-25',
    source_url: null,
    source_name: '広島ドラゴンフライズ公式',
    notes: null,
  },
  {
    id: '8',
    player_name: '多嶋 朝飛',
    from_team: '北海道',
    to_team: null,
    status: 'departure',
    announced_at: '2025-05-24',
    source_url: null,
    source_name: '北海道公式',
    notes: null,
  },
]
